default: &default
 adapter: postgresql
 encoding: unicode
 pool: 10
 port: 5432
 host: localhost
 username: root
 password: root

development:
 <<: *default
 database: chat-app

production:
 <<: *default
 database: chat-app